### GET ALL ITEMS
GET http://localhost:8000/items HTTP/1.1



### GET ITEM
GET http://localhost:8000/items/4 HTTP/1.1



### SET ITEM
POST http://localhost:8000/items HTTP/1.1
Content-Type: application/json

{
    "name": "NEW ITEM"
}

### DELETE ITEM
DELETE  http://localhost:8000/items/3 HTTP/1.1
